Update Dockerfile + build proccess, add workflow

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,29 +1,40 @@
 #!/usr/bin/env bash
 
 set -e
+PORT="4000"
+while getopts ":t:p:" opt; do
+  case $opt in
+    t) LFM_TOKEN = "$OPTARG"
+      ;;
+    p) PORT = "$OPTARG"
+      ;;
+    ?) echo "Invalid option -$OPTARG" >&2
+      exit 2
+      ;;
+    :) echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+if [ -z "$LFM_TOKEN" ]; then
+  echo "ERROR: Missing argument for token: -t [token]"
+  exit 1
+fi
 
-export MIX_ENV=$1
+printf "Starting release build...\r"
+cd /app
+sed -i "s/\${LFM_TOKEN}/\"$LFM_TOKEN\"/g" ./config/prod.env.exs
+sed -i "s/\${PORT}/\"$PORT\"/g" ./config/prod.env.exs
 
-echo "Starting release build for $MIX_ENV...\r"
-cd /opt/build
+printf "Fetching project dependencies...\r"
+mix local.rebar --if-missing --force > /dev/null
+mix local.hex --if-missing --force > /dev/null
+mix deps.get --only prod > /dev/null
+mix do clean, compile --force > /dev/null
 
-source ./.env
-export LFM_API_KEY
-sed -i "s/\${LFM_API_KEY}/\"$LFM_API_KEY\"/g" ./config/$MIX_ENV.env.exs
+printf "Building release...\r"
+export MIX_ENV = prod
+mix release prod --overwrite
 
-echo "Installing rebar3 and hex...\r"
-mix local.rebar --force
-mix local.hex --if-missing --force
-
-echo "Fetching project deps...\r"
-mix deps.get --only prod
-
-echo "Cleaning any leftover build artifacts...\r"
-mix do clean, compile --force
-
-echo "Building release for $MIX_ENV...\r"
-mix release $1 --overwrite
-
-echo "Release built successfully!\r"
-sed -i "s/\"$LFM_API_KEY\"/\${LFM_API_KEY}/g" ./config/$MIX_ENV.env.exs
+printf "Release built successfully!\r"
 exit 0
diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,59 +1,40 @@
 #!/bin/sh
 
+set -e
 MODE="prod"
-optstring=":m:"
 
-while getopts ${optstring} arg; do
-  case ${arg} in
-    m)
-      # check for valid mode after -m
-      if [ "$OPTARG" = "dev" ] || [ "$OPTARG" = "prod" ]; then
+while getopts ":m:" arg; do
+  case $opt in
+    m) if [ "$OPTARG" = "dev" ] || [ "$OPTARG" = "prod" ]; then
         MODE=$OPTARG
       else
-        echo "ERR: Invalid mode: $OPTARG"
+        echo "ERROR: Invalid mode: $OPTARG"
         exit 1
       fi
       ;;
-    :)
-      echo "ERR: Must supply an argument to -$OPTARG."
-      exit 1
-      ;;
-    ?)
-      echo "ERR: Invalid option: -${OPTARG}."
+    ?) echo "ERROR: Invalid option: -${OPTARG}."
       exit 2
+      ;;
+    :) echo "ERROR: Must supply an argument to -$OPTARG."
+      exit 1
       ;;
   esac
 done
 
 printf "Starting in $MODE mode...\r"
-
-# Check if CWD path 'bin' directory, if so, change to parent directory
 if [ "${PWD##*/}" = "bin" ]; then
   cd ..
 fi
 
-sleep 1
-
-printf "Installing Hex & rebar3...\r"
-mix local.hex --if-missing --force > /dev/null 2>&1
-mix local.rebar --force > /dev/null 2>&1
-
-# Install deps / install, hide output
-printf "Building dependencies...\r"
-mix deps.get > /dev/null 2>&1
-
-# If dev mode
 if [ "$MODE" = "dev" ]; then
-  # Start server w/ mix
+  printf "Building dependencies...\r"
+  mix local.hex --if-missing --force > /dev/null
+  mix local.rebar --if-missing --force > /dev/null
+  mix deps.get > /dev/null
   printf "\r"
-  # Get 'LFM_API_KEY' from .env file
-  source ./.env
-  export LFM_API_KEY
-
-  # MIX_ENV=$MODE mix run --no-halt
-  MIX_ENV=$MODE LFM_API_KEY=$LFM_API_KEY mix run --no-halt
+  source ./.env && MIX_ENV=$MODE mix run --no-halt
 else
-  # Build release
-  printf "Building release...\r"
-  # TODO
+  exec "/app/hexerei/${MODE}/rel/${MODE}/bin/prod" "start"
 fi
+
+exit 0
