chore: Update dockerfile, release, v1 route
- Rework dockerfile and build scripts
- Fix release opts
- Split out themes map from v1 route to assets dir, tidy error responses
  a bit

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,37 +1,9 @@
 #!/bin/sh
 
-set -e
-MODE="prod"
-while getopts ":m:" opt; do
-  case "${opt}" in
-    m) if [ "${OPTARG}" = "dev" ] || [ "${OPTARG}" = "prod" ]; then
-        MODE=${OPTARG}
-      else
-        echo "ERROR: Invalid mode \"${OPTARG}\""
-        exit 1
-      fi
-      ;;
-    ?) echo "ERROR: Invalid option \"-${OPTARG}\""
-      exit 2
-      ;;
-    *) echo "ERROR: Must supply an argument to \"-${OPTARG}\""
-      exit 1
-      ;;
-  esac
-done
-printf "Starting in ${MODE} mode...\r"
-if [ "${PWD##*/}" = "bin" ]; then
-  cd ..
+source ./.env
+if [ -z "${LFM_TOKEN}" ]; then
+  echo "ERROR: Missing or invalid argument token"
+  exit 1
 fi
-if [ "${MODE}" = "dev" ]; then
-  printf "Building dependencies...\r"
-  mix local.hex --if-missing --force > /dev/null
-  mix local.rebar --if-missing --force > /dev/null
-  mix deps.get > /dev/null
-  mix deps.compile > /dev/null
-  printf "\r"
-  source ./.env && MIX_ENV=${MODE} LFM_TOKEN=${LFM_TOKEN} mix run --no-halt
-else
-  exec "/app/toru/prod/rel/prod/bin/prod" "start"
-fi
+MIX_ENV="dev" LFM_TOKEN=${LFM_TOKEN} mix run --no-halt
 exit 0
